openapi: 3.1.0
info:
  title: PS-Wiki API
  version: 1.0.0
  description: Read-only API to browse PS-Wiki terms for use with ChatGPT Actions.
  license:
    name: CC BY-NC 4.0
    url: https://creativecommons.org/licenses/by-nc/4.0/
servers:
  - url: https://pswiki-api.jinninggm.workers.dev

# Explicitly declare "no authentication required" for all operations
security: []

paths:
  /v1/terms:
    get:
      operationId: listTerms
      summary: Search or list terms
      description: Matches id, title, description (as summary), and tags.
      parameters:
        - in: query
          name: query
          schema: { type: string }
          description: Free-text query.
        - in: query
          name: tag
          schema: { type: string }
          description: Filter by exact tag (case-insensitive).
        - in: query
          name: limit
          schema: { type: integer, minimum: 1, maximum: 100, default: 20 }
        - in: query
          name: cursor
          schema: { type: string }
          description: Opaque pagination cursor from a previous response.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: "#/components/schemas/TermSummary"
                  next_cursor:
                    type: [string, "null"]
        "400":
          description: Bad request (invalid parameter)
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }

  /v1/terms/{id}:
    get:
      operationId: getTerm
      summary: Get a term by id
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Term"
        "404":
          description: Not found
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }
        "400":
          description: Bad request (missing/invalid id)
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }

  /v1/terms/{id}/bib:
    get:
      operationId: getTermBibliography
      summary: Get bibliography for a term
      description: >
        Returns the term's cited references in the requested format. By default,
        only entries actually cited by the term (via `content.sections[*].source_keys`) are returned.
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
        - in: query
          name: format
          schema:
            type: string
            enum: [bibtex, csl-json, ris]
          description: Output format (default: bibtex). Also negotiable via Accept header.
        - in: query
          name: scope
          schema:
            type: string
            enum: [used, all]
            default: used
          description: used = only cited by this term; all = all references associated with the term.
      responses:
        "200":
          description: OK
          content:
            application/x-bibtex:
              schema:
                type: string
                description: Concatenated BibTeX entries
            application/vnd.citationstyles.csl+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CslItem"
            application/x-research-info-systems:
              schema:
                type: string
                description: RIS text
        "404":
          description: Term or references not found
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }
        "400":
          description: Bad request (invalid format/scope)
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }

  /v1/terms/{id}/sources:
    get:
      operationId: getTermSources
      summary: Get structured source metadata for a term
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
        - in: query
          name: scope
          schema:
            type: string
            enum: [used, all]
            default: used
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items: { $ref: "#/components/schemas/CslItem" }
        "404":
          description: Not found
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }
        "400":
          description: Bad request
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }

  /v1/tags:
    get:
      operationId: listTags
      summary: List tags and counts
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  tags:
                    type: array
                    items:
                      type: object
                      properties:
                        tag: { type: string }
                        count: { type: integer }
        "400":
          description: Bad request
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }

  /v1/changes:
    get:
      operationId: listChanges
      summary: Terms updated since timestamp
      parameters:
        - in: query
          name: since
          required: true
          schema: { type: string, format: date-time }
          description: ISO 8601 timestamp or date (YYYY-MM-DD).
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        id: { type: string }
                        updated_at: { type: string }
        "400":
          description: Bad request (missing/invalid `since`)
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }

components:
  schemas:
    TermSummary:
      type: object
      required: [id, title, updated_at]
      additionalProperties: false
      properties:
        id: { type: string }
        title: { type: string }
        summary: { type: string }
        tags:
          type: array
          items: { type: string }
        updated_at: { type: string, description: "ISO date (YYYY-MM-DD)" }

    Term:
      type: object
      description: Full term JSON as stored in database/json/<id>.json.
      additionalProperties: true

    CslItem:
      type: object
      additionalProperties: true
      properties:
        id: { type: string, description: "Bib key (e.g., nerc2024ltra)" }
        type: { type: string }
        title: { type: string }
        author:
          type: array
          items:
            type: object
            properties:
              given: { type: string }
              family: { type: string }
        issued:
          type: object
          properties:
            "date-parts":
              type: array
              items:
                type: array
                items: { type: integer }
        URL: { type: string }
        container-title: { type: string }
        bibtex_raw: { type: string, description: "Original BibTeX text for this entry, if available." }

    Error:
      type: object
      additionalProperties: true
      properties:
        error: { type: string }
        message: { type: string }
        status: { type: integer }
